services:
  frontend:
    build:
      context: ./pz-cheeseria-frontend
    ports:
      - "3000:80" # Map port 3000 on the container to 80 on your host machine
    volumes:
      - ./pz-cheeseria-frontend:/app # Mount local directory to container
      - /app/node_modules 
    environment:
      - CHOKIDAR_USEPOLLING=true # Enable polling for file changes (important for Docker)

  backend:
    build: ./pz-cheeseria-backend
    ports:
      - "3001:3001" # Map port 3001 in container to port 3001 on host
